dist: xenial
sudo: required
language: node_js
node_js:
  - '12'

services:
  - docker

cache: npm

matrix:
  fast_finish: true

before_install:
  - npm install -g npm
  - npm install -g ganache-cli@~6.5.1

before_script:
  - ganache-cli --port 18545 > ganache-cli.log &

script:
  - npm run lint
  - npm run build:metadata

notifications:
  email: false